version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - card-editor
    networks:
      - web-network

  card-editor:
    image: ${DOCKER_USERNAME}/card-editor-next:latest
    container_name: card-editor-next
    expose:
      - 3000
    environment:
      - NODE_ENV=production
    networks:
      - web-network

networks:
  web-network:
    driver: bridge 